### ISSUE TITLE
Using last stable api (v0) fetches master

### ISSUE THREAD

**Issue by srid** [hpcloud/tail#55]
A `go get gopkg.in/ActiveState/tail.v0` (to use the old stable API) will also fetch the master repo, which is due to the import of the fullly-qualified "github.com/ActiveState/tail/..." URL in several .go files. 

Replacing them with relative URLs does not work at all:

```
> make fulltest
[...]
can't load package: /go/src/github.com/ActiveState/tail/tail.go:15:2: local import "./ratelimiter" in non-local package
```

Consequently it becomes impossible to `go get` on the old API unless the user manually clones the repo under `$GOPATH/src/github.com/ActiveState/tail`

(this shouldn't affect the Stackato folks who use git commit hash to clone the repo)

**Comment by jandubois** [comment]
> A go get gopkg.in/ActiveState/tail.v0 (to use the old stable API)

Sorry, I can't really pay attention to this right now, but I don't think you should have to append a `.v0` to get the old API.  That needs to be the default, and you have to use whatever tag to get the new API. Otherwise this is not really backwards compatible:

Backwards compatible means old code continues to work **without** **any**w modification. Otherwise you are really just hijacking the namespace.

Sorry, if I'm totally misunderstanding what is going on, but this is triggering the backwards compatibility alarm bells:

> (this shouldn't affect the Stackato folks who use git commit hash to clone the repo)

Changes should not affect **any** existing users of the package.

**Comment by srid** [comment]
We never had stated gopkg.in support, so your question must be pertaining to those who do `import "github.com/ActiveState/tail". If you understand how go imports work, you will see how backwoard-compat is not supported by the official Go toolchain. Essentially - `go get` (which is used to fetch imported dependencies) *always* fetches git master HEAD of the specified repo URL.

(This is why we have goget.manifest in the Stackato Go repos; to specify the commit hash to fetch, instead of git master HEAD).

Apparently gopkg.in was designed to work around this shortcoming in the official toolchain. I'm sure there must be blog posts written on this topic.

> Changes should not affect any existing users of the package.

Once this issue is fixed, and users start using `import gopkg.in/ActiveState/tail.v<N>` in place of `import github.com/ActiveState/tail` we can guarantee this.

**Comment by jandubois** [comment]
> If you understand how go imports work, you will see how backwoard-compat is not supported by the official Go toolchain.

Yes, that is my point.  http://golang.org/doc/faq#get_version says:

> Packages intended for public use should try to maintain backwards compatibility as they evolve.

So if you cannot maintain backwards compatibility, you should use a new name for the incompatible new version instead of re-using the existing name. A new name is no burden: code using the new API needs to be changed anyways (or hasn't been written yet). So why break re-compilation of existing old code?

**Comment by srid** [comment]
By "new name" do you mean forking into a new repo (eg:
github.com/ActiveState/tail2)?

**Comment by jandubois** [comment]
> By "new name" do you mean forking into a new repo (eg:
> github.com/ActiveState/tail2)?

Yes, that seems to be the cleanest way to avoid breaking compatibility.

And then add a note to the `tail` repo that explains that `tail` is deprecated and the incompatible, but improved implementation is in `tail2`.

**Comment by srid** [comment]
We come full circle back to using gopkg.in ... which, too, solves the
backwards-compat issue but in a more acceptable manner. Acceptable, because
there is no need to keep creating new repos for newer API versions
(tail1.git, tail2.git. tail3.git).

I haven't looked in detail, but it appears that Go developers are using
something like gopkg.in instead of creating new repos; are there any Go
package in the wild that creates new repos for changed API?

The only (arguably minor) downside is that *existing* users will have to
migrate to importing from `gopkg.in/ActiveState/tail.v<N>` instead of the
direct URL. From that point onwards, backwards-compat is automatically
ensured.

**Comment by Nino-K** [comment]
I'm going to close this as it does not indicate a real issue.
